config/routes.rb
Rails.application.routes.draw do
    devise_for :employees
	root to: "dashboards#index"
	post '/dashboards/check_in', :to => 'dashboards#check_in'
	post '/dashboards/check_out', :to => 'dashboards#check_out'
	resources :admins
	resources :dashboards
	resources :messages
	mount ActionCable.server => '/cable'

# devise_scope :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Admin.rb
class Admin < Employee
	
end

app/models/admin.rb
class Admin < Employee
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance_time.rb
class AttendanceTime < ApplicationRecord
	belongs_to :employee
end

app/models/check_in.rb
class CheckIn < AttendanceTime
	
end

app/models/check_out.rb
class CheckOut < AttendanceTime
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :check_ins
  has_many :check_outs
  has_many :attendance_times
  has_many :messages, class_name: "Message", foreign_key: "recipient_id"
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"

  scope :except_admins, -> { where.not(type: "Admin") }
  
  STATUSES = {
    0 => "Not_Available",
    1 => "Available"
  }
  
  def is_checked_in?
    self.get_presence_status == "Available"
  end

  def is_checked_out?
    self.get_presence_status == "Not_Available"
  end

  def get_presence_status
    return STATUSES[self.presence_status]
  end

  def check_in!
    self.update_column(:presence_status, 1)
  end

  def check_out!
     self.update_column(:presence_status, 0)
  end
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :recipient, class_name: "Employee", foreign_key: "recipient_id"
   	belongs_to :sender, class_name: "Employee", foreign_key: "sender_id"
   	# scope :unread, -> { where read: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :null_session
	before_action :authenticate_employee!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index 
  end

  def check_in
    if current_employee.check_ins.new.save
      current_employee.check_in!
      ActionCable.server.broadcast 'attendance_time_channel',
        status: t("generic.#{current_employee.get_presence_status}"),
        employee_id: current_employee.id
      # head :ok
    end
    redirect_to dashboards_path
  end

  def check_out
    if current_employee.check_outs.new.save
      current_employee.check_out!
      ActionCable.server.broadcast 'attendance_time_channel',
        status: t("generic.#{current_employee.get_presence_status}"),
        employee_id: current_employee.id
      # head :ok
    end
    redirect_to dashboards_path
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def show

	end

	def check_in
		current_employee.check_ins.create
		current_employee.update_attribute('presence_status', 1)
		redirect_to employees_show_path
	end

	def check_out
		current_employee.check_outs.create
		current_employee.update_attribute('presence_status', 0)
		redirect_to employees_show_path
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionView::Helpers::SanitizeHelper
  def index
    @message = current_employee.sent_messages.new
    if current_employee.type != 'Admin'
      @recipient = helpers.get_latest_admin
    end
  end

  def create
    @message = current_employee.sent_messages.new message_params
    if @message.save
      flash[:success] = "Your message has been sent!"
      redirect_to messages_path
    else
      flash[:failure] = "Please try again."
      redirect_to messages_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :recipient_id)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
	def get_employee_list
		return Employee.except_admins
	end

	def get_latest_admin
		Admin.last
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
	def get_email_using_id(id)
		Employee.where(:id => id).pluck(:email)
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
	def get_conversation_between(sender, recipient)
		# Message.where((:sender_id => sender.id or :sender_id => recipient.id ) and (:recipient_id => sender.id or :recipient_id => recipient_id.id )).reverse
		Message.where("sender_id = ? and recipient_id = ? or sender_id = ? and recipient_id = ?", sender.id, recipient.id, recipient.id, sender.id)
	end
end

app/views/admins/show.html.erb
You are logged in as Admin
<b>
    <%= current_employee.email %></b>
<%= link_to('Logout', destroy_employee_session_path, method: :delete) %>
<table style="width:100%">
    <tr>
        <td><b>Email</b></td>
        <td><b>Status</b></td>
        <!-- <td><b>Check In</b></td> -->
    </tr>
    <% @employees.each do |employee|%>
    <tr>
        <td>
            <%= employee.email%>
        </td>
        <td>
            <% if employee.checked_in? %>
            Present
            <% else %>
            Absent
            <% end %>
        </td>
        <!-- <td> -->
        <%# if employee.check_ins.present? %>
        <%#= employee.check_ins.last.created_at > employee.check_outs.last.created_at ? employee.check_ins.last.created_at.strftime("%d %B %Y , %l:%M %p") : 'Not Came back' %>
        <%# end %>
        <!-- </td> -->
    </tr>
    <% end %>
</table>

app/views/dashboards/index.html.erb
<% if current_employee.class.name == 'Admin'%>
<%= render "dashboards/partials/admin_dashboard" %>
<% else %>
<%= render "dashboards/partials/employee_dashboard" %>
<% end %>
<%= link_to("Messages", messages_path)%>

app/views/dashboards/partials/_admin_dashboard.html.erb
<%= action_cable_meta_tag %>
<table style="width:100%">
    <tr>
        <td><b>
                <%= t("generic.Email") %> </b></td>
        <td><b>
                <%= t("generic.Status") %> </b></td>
    </tr>
    <%= render get_employee_list %>
</table>

app/views/dashboards/partials/_employee_dashboard.html.erb
<% if current_employee.is_checked_in? %>
<%= form_with(url: dashboards_check_out_path, method: "post") do |form| %>
<%= form.submit t("generic.Check_Out") %>
<% end %>
<% else %>
<%= form_with(url: dashboards_check_in_path, method: "post") do |form| %>
<%= form.submit t("generic.Check_In") %>
<% end %>
<% end %>

<br><br>

app/views/employees/_employee.html.erb
<tr data-id="<%= employee.id %>">
    <td class="user_email">
        <%=  employee.email %>
    </td>
    <td class="user_attendance_status">
    	<%= t("generic.#{employee.get_presence_status}") %>
    </td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>EmployeeAttendanceTimeDetail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% if current_employee.present? %>
    You are logged in as
    <%= current_employee.class.name %><b>
        <%= current_employee.email %></b>
    <%= link_to('Logout', destroy_employee_session_path, method: :delete) %>
    <br><br>
    <% end %>
    <%= yield %>
</body>

</html>

app/views/messages/index.html.erb
<%#= form_with model: @user do |form| %>
<%#= form.text_field :email %>
<%#= form.submit %>
<%# end %>
<% if current_employee.type == "Admin"%>
	<%= render "messages/partials/admin_messages" %>
<% else %>
	<%= render "messages/partials/employee_messages" %>
<% end%>

app/views/messages/partials/_admin_messages.html.erb
<h3>Employee Messages:-</h3>
<% get_employee_list.each do  |emp| %>
	<% if emp.messages.present? or emp.sent_messages.present? %>
		<h4>
		    <%= emp.email %>
		</h4>
		<% get_conversation_between(emp,current_employee).each do  |msg| %>
			<%= get_email_using_id(msg.sender.id) %>: <%= msg.content %><br>
		<% end %>
		<%= form_with(model: @message, method: "post") do |form| %>
			<%= form.text_field :content %>
			<%= form.hidden_field :recipient_id, value: emp.id %>
			<%= form.submit t("generic.Send_Message") %>
		<% end %>
	<% end %>
<% end %>

app/views/messages/partials/_employee_messages.html.erb
<% get_conversation_between(get_latest_admin,current_employee).each do  |msg| %>
	<%= get_email_using_id(msg.sender.id) %>: <%= msg.content %><br>
<% end %>

<%= form_with(model: @message, method: "post") do |form| %>
<%= form.text_field :content %>
<%= form.hidden_field :recipient_id, value: @recipient.id %>
<%= form.submit t("generic.Send_Message") %>
<% end %>